# Generated by Django 5.2 on 2025-05-17 21:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Tipo de Veículo')),
                ('capacidade_carga', models.FloatField(verbose_name='Capacidade (kg)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para fretes?')),
                ('avaliacao', models.FloatField(blank=True, null=True, verbose_name='Avaliação Média')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CNH')),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização Atual')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('user', models.OneToOneField(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Motorista',
                'verbose_name_plural': 'Perfis de Motoristas',
                'db_table': 'drivers_driverprofile',
            },
        ),
    ]
