# Generated by Django 5.2 on 2025-07-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='cnh',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Nome completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='numero_carta_conducao',
            field=models.CharField(default='Desconhecido', max_length=20, verbose_name='Número da Carta de Condução'),
            preserve_default=False,
        ),
    ]
