# Generated by Django 5.2 on 2025-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driverprofile_cnh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Província'),
        ),
    ]
