# Generated by Django 5.2 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do motorista', max_length=255, null=True),
        ),
    ]
