# Generated by Django 5.2 on 2025-05-24 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(help_text='Número no formato +258XXXXXXXXX ou 258XXXXXXXXX', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato +258XXXXXXXXX ou 258XXXXXXXXX.', regex='^(\\+?258)\\d{9}$')]),
        ),
    ]
