# Generated by Django 5.2 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do usuário', max_length=255, null=True, unique=True),
        ),
    ]
