# Generated by Django 5.2 on 2025-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_data_nascimento_clientprofile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Província'),
        ),
    ]
