# Generated by Django 5.2 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do cliente', max_length=255, null=True),
        ),
    ]
