# Generated by Django 5.2 on 2025-05-17 21:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cliente', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_client', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
